version: '3.8'

networks:
  k6:

services:
  app-1:
    image: app1:0.0.1
    container_name: app1
    build:
      context: ./app-1
      dockerfile: Dockerfile
    networks:
      - k6
    ports:
      - "8887:8080"
  app-2:
    image: app2:0.0.1
    container_name: app2
    build:
      context: ./app-2
      dockerfile: Dockerfile
    networks:
      - k6
    ports:
      - "8888:8080"
  prometheus:
    image: prom/prometheus:v2.47.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - k6
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:10.1.2
    networks:
      - k6
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - DS_PROMETHEUS=prometheus
    volumes:
      - ./grafana:/etc/grafana/provisioning/