server.port: 8080

spring:
  application:
    name: app-2

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
